// <auto-generated />
using System;
using MetricsApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetricsApi.Repository.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260718161035_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricsApi.Domain.Models.ResultMetric", b =>
                {
                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeSpan>("AvgDuration")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("DeltaTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("FirstStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ValueMax")
                        .HasColumnType("double precision");

                    b.Property<double>("ValueMean")
                        .HasColumnType("double precision");

                    b.Property<double>("ValueMedian")
                        .HasColumnType("double precision");

                    b.Property<double>("ValueMin")
                        .HasColumnType("double precision");

                    b.HasKey("FileName");

                    b.HasIndex("AvgDuration");

                    b.HasIndex("FirstStartTime");

                    b.HasIndex("ValueMean");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("MetricsApi.Domain.Models.ValueRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FileName", "StartTime");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
